experiment:
  summary: binary classification - feature  and model selection (final experiment)
  classification_type: binary
  stage: selection # feature and model selection
  tag: final
  verbosity: 0
  random_seed: 42

data:
  dataset_path: ../dataset/Sudoscan Working File with Stats.xlsx

feature_selection:
  cross_validation:
    k_splits: 4
    n_repeats: 10
    sort_by: auprc
  vif_threshold: 5

figures:
  summary_table_topk: 5